import React, { useContext, useState } from 'react';
import { AlertTriangle, ExternalLink, Languages, Loader2, Download, Printer, Globe2, Building2 } from 'lucide-react';
import { LanguageContext } from '../App';
import { Language } from '../types';

interface AnalysisResultProps {
  htmlContent: string;
  groundingMetadata?: any;
  onTranslate?: (targetLang: Language) => void;
  hideHeader?: boolean;
}

const AnalysisResult: React.FC<AnalysisResultProps> = ({ htmlContent, groundingMetadata, onTranslate, hideHeader }) => {
  const { t, language } = useContext(LanguageContext);
  const [isTranslating, setIsTranslating] = useState(false);

  const handleTranslateClick = async () => {
    if (onTranslate) {
      setIsTranslating(true);
      const target = language === 'en' ? 'ar' : 'en';
      await onTranslate(target);
      setIsTranslating(false);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  const handleDownload = () => {
    const fullHtml = `
      <!DOCTYPE html>
      <html lang="${language}" dir="${language === 'ar' ? 'rtl' : 'ltr'}">
      <head>
        <meta charset="UTF-8" />
        <title>CodeScout Pro - Due Diligence Report</title>
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&family=Cairo:wght@400;600;700&display=swap');
          body { 
            font-family: 'Inter', 'Cairo', sans-serif; 
            padding: 40px; 
            max-width: 900px; 
            margin: 0 auto; 
            color: #0f172a; 
            line-height: 1.5; 
            font-size: 12px;
          }
          .header { border-bottom: 2px solid #0f172a; padding-bottom: 20px; margin-bottom: 30px; display: flex; justify-content: space-between; align-items: flex-end; }
          .logo { font-size: 24px; font-weight: 800; text-transform: uppercase; letter-spacing: -0.5px; }
          .meta { text-align: right; color: #64748b; font-size: 10px; }
          
          /* Consistent Styles for Downloaded PDF/HTML */
          h2 { 
            font-size: 16px; 
            font-weight: 800; 
            border-bottom: 2px solid #334155; 
            padding-bottom: 8px; 
            margin-top: 30px; 
            margin-bottom: 15px; 
            color: #1e293b; 
            text-transform: uppercase; 
            letter-spacing: 0.5px; 
          }
          h3 { 
            font-size: 14px; 
            font-weight: 700; 
            color: #334155; 
            margin-top: 20px; 
            margin-bottom: 10px;
          }
          table { width: 100%; border-collapse: collapse; margin: 15px 0; font-size: 11px; border: 1px solid #cbd5e1; }
          th { background-color: #f1f5f9; text-align: left; padding: 10px; border: 1px solid #cbd5e1; font-weight: 700; color: #334155; text-transform: uppercase; }
          td { padding: 10px; border: 1px solid #cbd5e1; vertical-align: top; color: #334155; }
          tr:nth-child(even) { background-color: #f8fafc; }
          
          /* RTL Fixes */
          html[dir="rtl"] th, html[dir="rtl"] td { text-align: right; }
          
          .footer { margin-top: 50px; border-top: 1px solid #e2e8f0; padding-top: 15px; font-size: 9px; color: #94a3b8; text-align: center; }
          .disclaimer { background: #fff7ed; padding: 10px; border: 1px solid #ffedd5; color: #c2410c; margin-top: 20px; font-size: 10px; }
        </style>
      </head>
      <body>
        <div class="header">
          <div class="logo">CodeScout<span style="color:#2563eb">PRO</span></div>
          <div class="meta">
            REPORT ID: ${Math.random().toString(36).substr(2, 9).toUpperCase()}<br/>
            DATE: ${new Date().toLocaleDateString()}<br/>
            CONFIDENTIAL
          </div>
        </div>
        
        <div class="report-content">
          ${htmlContent}
        </div>

        <div class="disclaimer">
           This automated report is for informational purposes only. Verification with official municipal sources is required.
        </div>

        <div class="footer">
          Generated by CodeScout Pro AI Neural Engine | Enterprise Edition
        </div>
      </body>
      </html>
    `;

    const blob = new Blob([fullHtml], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `CodeScout_Official_Report_${new Date().toISOString().slice(0, 10)}.html`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  // Inline styles to force consistency in the rendered view
  const reportStyles = `
  .report-content h2 {
    font-size: 1.25rem;
    font-weight: 800;
    color: #1e293b;
    border-bottom: 2px solid #334155;
    padding-bottom: 0.5rem;
    margin-top: 2.5rem;
    margin-bottom: 1.5rem;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    font-family: inherit;
  }
  .report-content h3 {
    font-size: 1.1rem;
    font-weight: 700;
    color: #334155;
    margin-top: 1.5rem;
    margin-bottom: 1rem;
    display: flex;
    align-items: center;
    font-family: inherit;
  }
  .report-content h3::before {
    content: '';
    display: inline-block;
    width: 4px;
    height: 1.2em;
    background-color: #2563eb; /* Brand Blue */
    margin-right: 0.75rem;
    border-radius: 2px;
  }
  .report-content table {
    width: 100%;
    border-collapse: collapse;
    margin: 1.5rem 0;
    font-size: 0.9rem;
    background: #fff;
    border: 1px solid #cbd5e1;
  }
  .report-content th {
    background-color: #f1f5f9;
    color: #475569;
    font-weight: 700;
    text-transform: uppercase;
    font-size: 0.75rem;
    padding: 1rem;
    text-align: left;
    border: 1px solid #cbd5e1;
    letter-spacing: 0.05em;
  }
  .report-content td {
    padding: 1rem;
    border: 1px solid #cbd5e1;
    color: #334155;
    vertical-align: top;
    line-height: 1.6;
  }
  .report-content tr:nth-child(even) {
    background-color: #f8fafc;
  }
  .report-content ul {
    list-style-type: disc;
    padding-left: 1.5rem;
    margin-bottom: 1.5rem;
    color: #475569;
  }
  .report-content li {
    margin-bottom: 0.5rem;
  }
  .report-content p {
    margin-bottom: 1rem;
    line-height: 1.7;
    color: #475569;
    text-align: justify;
    font-size: 1rem;
  }
  /* RTL Support */
  [dir="rtl"] .report-content h3::before {
    margin-right: 0;
    margin-left: 0.75rem;
  }
  [dir="rtl"] .report-content th, [dir="rtl"] .report-content td {
    text-align: right;
  }
  [dir="rtl"] .report-content ul {
    padding-left: 0;
    padding-right: 1.5rem;
  }
`;

  return (
    <div className={`bg-white rounded-lg shadow-xl print:shadow-none border border-slate-200 overflow-hidden ${hideHeader ? 'shadow-none border-none' : ''}`}>
      <style>{reportStyles}</style>
      
      {/* Official Header */}
      {!hideHeader && (
        <div className="bg-slate-900 text-white p-6 flex flex-col md:flex-row justify-between items-start md:items-center gap-4 print:hidden">
          <div>
            <h2 className="text-lg font-bold font-cairo tracking-wide flex items-center gap-2 !m-0 !border-0 !pb-0">
              <Building2 className="w-5 h-5 text-brand-400" />
              {language === 'ar' ? 'تقرير العناية الواجبة' : 'Due Diligence Report'}
            </h2>
            <div className="text-[10px] text-slate-400 mt-1 font-mono uppercase tracking-widest flex items-center gap-2">
              <span className="w-1.5 h-1.5 rounded-full bg-green-500 animate-pulse"></span>
              {language === 'ar' ? 'تم الإنشاء آلياً' : 'Automated Generation'}
            </div>
          </div>
          <div className="flex items-center gap-2">
            <button 
              onClick={handleDownload}
              className="flex items-center gap-2 text-xs font-bold bg-white/10 hover:bg-white/20 text-white px-4 py-2 rounded border border-white/10 transition"
            >
              <Download className="w-3.5 h-3.5" />
              {t.downloadReport || "Download"}
            </button>
            
            <button 
              onClick={handlePrint}
              className="flex items-center gap-2 text-xs font-bold bg-white text-slate-900 px-4 py-2 rounded border border-white transition hover:bg-slate-100"
            >
              <Printer className="w-3.5 h-3.5" />
              {t.printReport || "Print"}
            </button>

            {onTranslate && (
              <button 
                onClick={handleTranslateClick}
                disabled={isTranslating}
                className="flex items-center gap-2 text-xs font-bold bg-brand-600 hover:bg-brand-500 text-white px-4 py-2 rounded border border-transparent transition disabled:opacity-50"
              >
                {isTranslating ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Languages className="w-3.5 h-3.5" />}
                {t.translateTo}
              </button>
            )}
          </div>
        </div>
      )}

      {/* Main Content (Paper view) */}
      <div className={`${hideHeader ? 'p-0' : 'p-12'} overflow-x-auto print:p-0 bg-white min-h-[600px]`}>
        
        <div className={`mx-auto ${hideHeader ? '' : 'max-w-3xl'}`}>
            {/* Print Header */}
            <div className="hidden print:flex justify-between items-end mb-10 border-b-2 border-black pb-6">
                <div>
                    <h1 className="text-2xl font-black text-black tracking-tight uppercase">CodeScout Pro</h1>
                    <p className="text-xs text-gray-500 mt-1">Urban Intelligence Unit</p>
                </div>
                <div className="text-right text-[10px] text-gray-500">
                    <div>Ref: {Math.random().toString(36).substring(7).toUpperCase()}</div>
                    <div>Date: {new Date().toLocaleDateString()}</div>
                </div>
            </div>

            <div 
            className="report-content"
            dir={language === 'ar' ? 'rtl' : 'ltr'}
            dangerouslySetInnerHTML={{ __html: htmlContent }} 
            />

            {/* Print Footer */}
            <div className="hidden print:block mt-16 pt-4 border-t border-gray-200 text-[9px] text-center text-gray-400 uppercase tracking-wider">
                System Generated Report - Verification Required
            </div>
        </div>
      </div>

      {/* Grounding Sources Footer */}
      {groundingMetadata && groundingMetadata.groundingChunks && (
        <div className={`bg-slate-50 p-8 border-t border-slate-200 print:hidden ${hideHeader ? 'mt-8' : ''}`}>
          <div className="flex items-center gap-3 mb-4">
             <div className="w-6 h-6 bg-white border border-slate-300 rounded flex items-center justify-center shadow-sm">
                <ExternalLink className="w-3 h-3 text-slate-600" />
             </div>
             <h4 className="text-xs font-bold text-slate-700 uppercase tracking-wide">
                {language === 'ar' ? 'المراجع الرسمية' : 'Official References'}
             </h4>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            {groundingMetadata.groundingChunks.map((chunk: any, index: number) => {
              if (chunk.web?.uri) {
                 return (
                  <a 
                    key={index} 
                    href={chunk.web.uri} 
                    target="_blank" 
                    rel="noopener noreferrer"
                    className="flex items-center gap-2 p-2 bg-white border border-slate-200 rounded hover:border-brand-300 hover:text-brand-700 transition text-xs text-slate-600 truncate"
                  >
                    <Globe2 className="w-3 h-3 shrink-0 text-slate-400" />
                    <span className="truncate">{chunk.web.title || chunk.web.uri}</span>
                  </a>
                );
              }
              return null;
            })}
          </div>
          
          <div className="mt-6 p-3 bg-amber-50 border border-amber-200 rounded text-[11px] text-amber-800 flex items-start gap-2">
            <AlertTriangle className="w-4 h-4 shrink-0 text-amber-600" />
            <p className="leading-tight">
              {language === 'ar' 
                ? 'إخلاء مسؤولية: هذا التقرير استرشادي وتم إنشاؤه بواسطة الذكاء الاصطناعي. يجب مراجعة الجهات المختصة للاعتماد النهائي.'
                : 'Disclaimer: This report is advisory. Final approval lies with the relevant municipal authority. Verify all citations.'}
            </p>
          </div>
        </div>
      )}
    </div>
  );
};

export default AnalysisResult;